# Generated by Django 6.0.3 on 2026-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='token',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='verification_code',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
