# Generated by Django 6.0.3 on 2026-04-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_notification_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
