# Generated by Django 6.0.3 on 2026-05-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_institute_academic_year_institute_address_and_more"),
        ("lms", "0007_announcement_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="academic_year",
            field=models.CharField(
                blank=True, help_text="e.g., 2025-2026", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="section",
            field=models.CharField(
                default="A", help_text="Course section (A, B, C, etc.)", max_length=20
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={
                ("institute", "code", "semester", "academic_year", "section")
            },
        ),
    ]
